"""add_installments_and_invoice_type

Revision ID: 6e4876a9a7e8
Revises: 0005_invoice_client_optional
Create Date: 2026-05-12 03:40:11.958511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e4876a9a7e8'
down_revision: Union[str, None] = '0005_invoice_client_optional'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts_payable', sa.Column('installment_number', sa.Integer(), nullable=True))
    op.add_column('accounts_payable', sa.Column('installment_total', sa.Integer(), nullable=True))
    op.add_column('accounts_receivable', sa.Column('installment_number', sa.Integer(), nullable=True))
    op.add_column('accounts_receivable', sa.Column('installment_total', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('invoice_type', sa.String(length=50), nullable=False, server_default='venda'))
    op.add_column('invoices', sa.Column('installment_number', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('installment_total', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('parent_invoice_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_invoices_parent_invoice_id'), 'invoices', ['parent_invoice_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'invoices', ['parent_invoice_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('idx_receipt_purchase_order_id'), table_name='purchase_order_receipts')
    op.drop_index(op.f('idx_receipt_purchase_order_item_id'), table_name='purchase_order_receipts')
    op.create_index(op.f('ix_purchase_order_receipts_purchase_order_id'), 'purchase_order_receipts', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_receipts_purchase_order_item_id'), 'purchase_order_receipts', ['purchase_order_item_id'], unique=False)
    op.add_column('purchase_orders', sa.Column('installments', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('purchase_orders', sa.Column('first_due_date', sa.Date(), nullable=True))
    op.add_column('purchase_orders', sa.Column('installment_interval_days', sa.Integer(), nullable=False, server_default='30'))
    op.add_column('sales', sa.Column('installments', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('sales', sa.Column('first_due_date', sa.Date(), nullable=True))
    op.add_column('sales', sa.Column('installment_interval_days', sa.Integer(), nullable=False, server_default='30'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'installment_interval_days')
    op.drop_column('sales', 'first_due_date')
    op.drop_column('sales', 'installments')
    op.drop_column('purchase_orders', 'installment_interval_days')
    op.drop_column('purchase_orders', 'first_due_date')
    op.drop_column('purchase_orders', 'installments')
    op.drop_index(op.f('ix_purchase_order_receipts_purchase_order_item_id'), table_name='purchase_order_receipts')
    op.drop_index(op.f('ix_purchase_order_receipts_purchase_order_id'), table_name='purchase_order_receipts')
    op.create_index(op.f('idx_receipt_purchase_order_item_id'), 'purchase_order_receipts', ['purchase_order_item_id'], unique=False)
    op.create_index(op.f('idx_receipt_purchase_order_id'), 'purchase_order_receipts', ['purchase_order_id'], unique=False)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_parent_invoice_id'), table_name='invoices')
    op.drop_column('invoices', 'parent_invoice_id')
    op.drop_column('invoices', 'installment_total')
    op.drop_column('invoices', 'installment_number')
    op.drop_column('invoices', 'invoice_type')
    op.drop_column('accounts_receivable', 'installment_total')
    op.drop_column('accounts_receivable', 'installment_number')
    op.drop_column('accounts_payable', 'installment_total')
    op.drop_column('accounts_payable', 'installment_number')
    # ### end Alembic commands ###
