"""add_installments_and_invoice_type

Revision ID: 6e4876a9a7e8
Revises: 0005_invoice_client_optional
Create Date: 2026-05-12 03:40:11.958511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e4876a9a7e8'
down_revision: Union[str, None] = '0005_invoice_client_optional'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Idempotente: a migration inicial (0001) usa Base.metadata.create_all, que já
    # cria o schema atual completo. Cada operação abaixo é guardada para permitir
    # `alembic upgrade head` em banco novo. Para colunas NOT NULL com default,
    # garantimos também o server_default (o create_all só aplica o default do ORM,
    # que é Python-side e não chega ao banco) — o seed depende desses defaults.

    # Colunas de parcelamento (nullable) em contas e faturas.
    op.execute("ALTER TABLE accounts_payable ADD COLUMN IF NOT EXISTS installment_number INTEGER")
    op.execute("ALTER TABLE accounts_payable ADD COLUMN IF NOT EXISTS installment_total INTEGER")
    op.execute("ALTER TABLE accounts_receivable ADD COLUMN IF NOT EXISTS installment_number INTEGER")
    op.execute("ALTER TABLE accounts_receivable ADD COLUMN IF NOT EXISTS installment_total INTEGER")

    # invoices.invoice_type NOT NULL DEFAULT 'venda'
    op.execute("ALTER TABLE invoices ADD COLUMN IF NOT EXISTS invoice_type VARCHAR(50) DEFAULT 'venda'")
    op.execute("ALTER TABLE invoices ALTER COLUMN invoice_type SET DEFAULT 'venda'")
    op.execute("UPDATE invoices SET invoice_type = 'venda' WHERE invoice_type IS NULL")
    op.execute("ALTER TABLE invoices ALTER COLUMN invoice_type SET NOT NULL")

    op.execute("ALTER TABLE invoices ADD COLUMN IF NOT EXISTS installment_number INTEGER")
    op.execute("ALTER TABLE invoices ADD COLUMN IF NOT EXISTS installment_total INTEGER")
    op.execute("ALTER TABLE invoices ADD COLUMN IF NOT EXISTS parent_invoice_id UUID")
    op.execute("CREATE INDEX IF NOT EXISTS ix_invoices_parent_invoice_id ON invoices (parent_invoice_id)")
    op.execute(
        """
        DO $$ BEGIN
          IF NOT EXISTS (
            SELECT 1 FROM pg_constraint
            WHERE conname = 'invoices_parent_invoice_id_fkey'
              AND conrelid = 'invoices'::regclass
          ) THEN
            ALTER TABLE invoices ADD CONSTRAINT invoices_parent_invoice_id_fkey
              FOREIGN KEY (parent_invoice_id) REFERENCES invoices(id) ON DELETE SET NULL;
          END IF;
        END $$;
        """
    )

    # purchase_order_receipts: renomeia índices idx_receipt_* -> ix_* (padrão atual).
    op.execute("DROP INDEX IF EXISTS idx_receipt_purchase_order_id")
    op.execute("DROP INDEX IF EXISTS idx_receipt_purchase_order_item_id")
    op.execute("CREATE INDEX IF NOT EXISTS ix_purchase_order_receipts_purchase_order_id ON purchase_order_receipts (purchase_order_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_purchase_order_receipts_purchase_order_item_id ON purchase_order_receipts (purchase_order_item_id)")

    # purchase_orders / sales: campos de parcelamento (installments NOT NULL DEFAULT 1,
    # installment_interval_days NOT NULL DEFAULT 30, first_due_date nullable).
    for tbl in ("purchase_orders", "sales"):
        op.execute(f"ALTER TABLE {tbl} ADD COLUMN IF NOT EXISTS installments INTEGER DEFAULT 1")
        op.execute(f"ALTER TABLE {tbl} ALTER COLUMN installments SET DEFAULT 1")
        op.execute(f"UPDATE {tbl} SET installments = 1 WHERE installments IS NULL")
        op.execute(f"ALTER TABLE {tbl} ALTER COLUMN installments SET NOT NULL")

        op.execute(f"ALTER TABLE {tbl} ADD COLUMN IF NOT EXISTS first_due_date DATE")

        op.execute(f"ALTER TABLE {tbl} ADD COLUMN IF NOT EXISTS installment_interval_days INTEGER DEFAULT 30")
        op.execute(f"ALTER TABLE {tbl} ALTER COLUMN installment_interval_days SET DEFAULT 30")
        op.execute(f"UPDATE {tbl} SET installment_interval_days = 30 WHERE installment_interval_days IS NULL")
        op.execute(f"ALTER TABLE {tbl} ALTER COLUMN installment_interval_days SET NOT NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'installment_interval_days')
    op.drop_column('sales', 'first_due_date')
    op.drop_column('sales', 'installments')
    op.drop_column('purchase_orders', 'installment_interval_days')
    op.drop_column('purchase_orders', 'first_due_date')
    op.drop_column('purchase_orders', 'installments')
    op.drop_index(op.f('ix_purchase_order_receipts_purchase_order_item_id'), table_name='purchase_order_receipts')
    op.drop_index(op.f('ix_purchase_order_receipts_purchase_order_id'), table_name='purchase_order_receipts')
    op.create_index(op.f('idx_receipt_purchase_order_item_id'), 'purchase_order_receipts', ['purchase_order_item_id'], unique=False)
    op.create_index(op.f('idx_receipt_purchase_order_id'), 'purchase_order_receipts', ['purchase_order_id'], unique=False)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_parent_invoice_id'), table_name='invoices')
    op.drop_column('invoices', 'parent_invoice_id')
    op.drop_column('invoices', 'installment_total')
    op.drop_column('invoices', 'installment_number')
    op.drop_column('invoices', 'invoice_type')
    op.drop_column('accounts_receivable', 'installment_total')
    op.drop_column('accounts_receivable', 'installment_number')
    op.drop_column('accounts_payable', 'installment_total')
    op.drop_column('accounts_payable', 'installment_number')
    # ### end Alembic commands ###
