"""expand_pcp_harvests_and_stock

Revision ID: a3a3566e9e09
Revises: 6e4876a9a7e8
Create Date: 2026-05-13 02:03:20.533933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3a3566e9e09'
down_revision: Union[str, None] = '6e4876a9a7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Expand production_order_status enum with new values.
    # ADD VALUE IF NOT EXISTS is safe and transactionless in PostgreSQL.
    op.execute("ALTER TYPE production_order_status ADD VALUE IF NOT EXISTS 'em_execucao'")
    op.execute("ALTER TYPE production_order_status ADD VALUE IF NOT EXISTS 'pausada'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_harvests',
    sa.Column('production_order_id', sa.UUID(), nullable=False),
    sa.Column('harvest_number', sa.Integer(), nullable=False),
    sa.Column('percentage_harvested', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sacks_total', sa.Numeric(precision=8, scale=2), nullable=False, server_default='0'),
    sa.Column('sacks_especial', sa.Numeric(precision=8, scale=2), nullable=False, server_default='0'),
    sa.Column('sacks_superior', sa.Numeric(precision=8, scale=2), nullable=False, server_default='0'),
    sa.Column('sacks_tradicional', sa.Numeric(precision=8, scale=2), nullable=False, server_default='0'),
    sa.Column('inputs_consumed', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('harvested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_harvests_production_order_id'), 'production_harvests', ['production_order_id'], unique=False)
    op.add_column('plot_activities', sa.Column('hours_spent', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('plot_activities', sa.Column('employee_id', sa.UUID(), nullable=True))
    op.add_column('plot_activities', sa.Column('quantity_applied', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('plot_activities', sa.Column('quantity_unit', sa.String(length=20), nullable=True))
    op.add_column('plot_activities', sa.Column('result', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_plot_activities_employee_id'), 'plot_activities', ['employee_id'], unique=False)
    op.create_foreign_key(None, 'plot_activities', 'employees', ['employee_id'], ['id'], ondelete='SET NULL')
    op.add_column('production_orders', sa.Column('order_number', sa.String(length=20), nullable=True))
    op.add_column('production_orders', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('production_orders', sa.Column('expected_end_date', sa.Date(), nullable=True))
    op.add_column('production_orders', sa.Column('responsible_employee_id', sa.UUID(), nullable=True))
    op.add_column('production_orders', sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    op.add_column('production_orders', sa.Column('realized_cost', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
    op.add_column('production_orders', sa.Column('harvest_progress', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0'))
    op.create_index(op.f('ix_production_orders_order_number'), 'production_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_production_orders_responsible_employee_id'), 'production_orders', ['responsible_employee_id'], unique=False)
    op.create_foreign_key(None, 'production_orders', 'employees', ['responsible_employee_id'], ['id'], ondelete='SET NULL')
    op.add_column('stock_items', sa.Column('hourly_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_items', 'hourly_cost')
    op.drop_constraint(None, 'production_orders', type_='foreignkey')
    op.drop_index(op.f('ix_production_orders_responsible_employee_id'), table_name='production_orders')
    op.drop_index(op.f('ix_production_orders_order_number'), table_name='production_orders')
    op.drop_column('production_orders', 'harvest_progress')
    op.drop_column('production_orders', 'realized_cost')
    op.drop_column('production_orders', 'estimated_cost')
    op.drop_column('production_orders', 'responsible_employee_id')
    op.drop_column('production_orders', 'expected_end_date')
    op.drop_column('production_orders', 'start_date')
    op.drop_column('production_orders', 'order_number')
    op.drop_constraint(None, 'plot_activities', type_='foreignkey')
    op.drop_index(op.f('ix_plot_activities_employee_id'), table_name='plot_activities')
    op.drop_column('plot_activities', 'result')
    op.drop_column('plot_activities', 'quantity_unit')
    op.drop_column('plot_activities', 'quantity_applied')
    op.drop_column('plot_activities', 'employee_id')
    op.drop_column('plot_activities', 'hours_spent')
    op.drop_index(op.f('ix_production_harvests_production_order_id'), table_name='production_harvests')
    op.drop_table('production_harvests')
    # Removing enum values from PostgreSQL requires recreating the type.
    # Only safe if no rows use 'em_execucao' or 'pausada'.
    op.execute("""
        ALTER TYPE production_order_status RENAME TO production_order_status_old;
        CREATE TYPE production_order_status AS ENUM (
            'planejada', 'em_producao', 'concluida', 'cancelada'
        );
        ALTER TABLE production_orders
            ALTER COLUMN status TYPE production_order_status
            USING status::text::production_order_status;
        DROP TYPE production_order_status_old;
    """)
    # ### end Alembic commands ###
